---
driver:
  name: vagrant
  attached_disks:
  - ["sdb.vmdk", "100", "1", "0", "hdd"]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: puppetlabs/centos-7.2-64-nocm

suites:
  - name: default
    run_list:
      - recipe[kafka::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
